test_that("rainfall plot retains the interactive composition", {
  plot <- rainfallPlot(brca_maf(), detectChangePoints = TRUE)
  spec <- plot$x$spec

  expect_s3_class(plot, "mutglyph")
  expect_identical(spec$name, "mutglyph-rainfall-plot")
  expect_identical(spec$width, "container")
  expect_identical(spec$height, "container")
  expect_identical(spec$assembly, "hg19")
  expect_identical(spec$title$text, "TCGA-A8-A08B")
  expect_named(spec$datasets, c("mutations", "kataegis"))
  expect_equal(nrow(spec$datasets$mutations), 1890)
  expect_equal(nrow(spec$datasets$kataegis), 7)
  expect_identical(
    vapply(spec$layer, `[[`, character(1), "name"),
    c("kataegis-intervals", "rainfall-mutations", "kataegis-arrows")
  )
  expect_true(spec$scales$x$zoom)
})

test_that("rainfall plot can suppress its autogenerated title", {
  spec <- rainfallPlot(brca_maf(), showTitle = FALSE)$x$spec

  expect_null(spec$title)
})

test_that("kataegis arrows start at the plot bottom and point upward", {
  arrow <- rainfallPlot(
    brca_maf(),
    detectChangePoints = TRUE
  )$x$spec$layer[[3]]

  expect_identical(arrow$mark$type, "arrow")
  expect_identical(arrow$encoding$y$field, "arrow_height")
  expect_identical(arrow$encoding$y2, list(value = 0))
  expect_identical(arrow$encoding$direction, list(value = "reverse"))
  expect_identical(arrow$encoding$x$pos, "start_position")
  expect_identical(arrow$encoding$x2$pos, "start_position")
})

test_that("kataegis shading encodes the complete locus", {
  interval <- rainfallPlot(
    brca_maf(),
    detectChangePoints = TRUE
  )$x$spec$layer[[1]]

  expect_identical(interval$mark$type, "rect")
  expect_identical(interval$encoding$x$pos, "start_position")
  expect_identical(interval$encoding$x2$pos, "end_position")
  expect_identical(interval$encoding$y, list(value = 1))
  expect_identical(interval$encoding$y2, list(value = 0))
})

test_that("rainfall plot uses chromosome-local distances", {
  mutations <- rainfallPlot(brca_maf())$x$spec$datasets$mutations
  chromosome_starts <- !duplicated(mutations$chromosome)

  # The unplottable first mutation of every chromosome was removed, so every
  # retained point has an actual predecessor on the same chromosome.
  expect_true(all(mutations$inter_event_distance >= 0))
  expect_true(all(is.finite(mutations$log10_distance)))
  expect_true(any(chromosome_starts))
})

test_that("rainfall JSON contains mutation and kataegis records", {
  json <- as_json(
    rainfallPlot(brca_maf(), detectChangePoints = TRUE),
    pretty = FALSE
  )
  decoded <- jsonlite::fromJSON(json, simplifyVector = FALSE)

  expect_length(decoded$datasets$mutations, 1890)
  expect_length(decoded$datasets$kataegis, 7)
})

test_that("rainfall plot accepts an initial genomic region", {
  spec <- rainfallPlot(
    brca_maf(),
    region = "chr8:98,000,000-98,500,000"
  )$x$spec

  expect_identical(
    spec$scales$x$domain,
    list(
      list(chrom = "chr8", pos = 98000000),
      list(chrom = "chr8", pos = 98500000)
    )
  )
  expect_true(spec$scales$x$zoom)
})

test_that("rainfall plot accepts arbitrary scored annotation tracks", {
  genes <- data.frame(
    seqnames = c("chr8", "chr8"),
    start = c(98000000, 98200000),
    end = c(98001000, 98202000),
    label = c("GENE1", "GENE2"),
    identifier = c("1", "2"),
    strand = c("+", "-"),
    score = c(10, 1)
  )
  spec <- rainfallPlot(
    brca_maf(),
    region = "chr8:98,000,000-98,500,000",
    annotationTracks = list(genes = genes)
  )$x$spec

  annotation_view <- spec$vconcat[[2]]
  annotation_body <- annotation_view$layer[[1]]
  expect_named(
    spec$datasets,
    c("mutations", "kataegis", "annotation_track_1")
  )
  expect_length(spec$vconcat, 2)
  expect_identical(spec$spacing, 15)
  expect_identical(spec$vconcat[[1]]$name, "rainfall-panel")
  expect_identical(annotation_view$name, "annotation-annotation_track_1")
  expect_identical(annotation_view$resolve$axis$x, "excluded")
  expect_identical(annotation_body$data$name, "annotation_track_1")
  expect_identical(annotation_body$mark$type, "arrow")
  expect_identical(annotation_body$mark$style, "arrow-block")
  expect_null(annotation_body$encoding$x$axis)
  expect_null(annotation_view$layer[[2]]$encoding$x$axis)
  expect_identical(annotation_body$encoding$direction$field, "strand")
  expect_identical(spec$resolve$scale$x, "shared")
  expect_identical(spec$resolve$scale$y, "independent")
  expect_identical(spec$resolve$axis$x, "independent")
  expect_identical(spec$vconcat[[1]]$resolve$axis$x, "shared")
})

test_that("rainfall display arguments validate", {
  maf <- brca_maf()

  expect_error(rainfallPlot(maf, savePlot = TRUE), "Save as SVG")
  expect_error(rainfallPlot(maf, savePlot = 1), "TRUE or FALSE")
  expect_error(rainfallPlot(maf, showTitle = 1), "TRUE or FALSE")
  for (value in list(0, -1, Inf, NA_real_, "1", c(1, 2))) {
    expect_error(
      rainfallPlot(maf, fontSize = value),
      "finite positive"
    )
    expect_error(
      rainfallPlot(maf, pointSize = value),
      "finite positive"
    )
  }
})
