#' Recurrent PIK3CA mutations in TCGA-BRCA
#'
#' A small, pre-aggregated example containing recurrent protein-altering
#' `PIK3CA` mutations in the TCGA breast invasive carcinoma cohort. Counts are
#' distinct tumor samples, after reducing TCGA aliquot barcodes to their
#' 16-character sample identifiers.
#'
#' The source is the open-access GDC TCGA-BRCA masked somatic mutation MAF
#' collection produced by the Aliquot Ensemble Somatic Variant Merging and
#' Masking workflow. Only canonical transcript `ENST00000263967`, directly
#' protein-altering variants are included. The coordinate is the first affected
#' residue parsed from `HGVSp_Short`, and only mutations observed in at least
#' two distinct samples are retained.
#'
#' The results shown here are in whole or part based upon data generated by the
#' TCGA Research Network: <https://www.cancer.gov/tcga>.
#'
#' @format A data frame with 26 rows and 6 columns:
#' \describe{
#'   \item{gene}{HGNC gene symbol; always `PIK3CA`.}
#'   \item{position}{First affected residue in canonical PIK3CA.}
#'   \item{mutation}{Short protein-change label.}
#'   \item{count}{Number of distinct TCGA tumor samples.}
#'   \item{variant_class}{GDC/MAF variant classification.}
#'   \item{source_protein_position}{Original GDC `Protein_position`.}
#' }
#'
#' @source
#' Mutation calls: [NCI Genomic Data Commons TCGA-BRCA](https://portal.gdc.cancer.gov/projects/TCGA-BRCA).
#' Protein coordinates refer to canonical PIK3CA transcript `ENST00000263967`
#' and UniProt accession [P42336](https://www.uniprot.org/uniprotkb/P42336/entry),
#' length 1,068 amino acids. Prepared on 2026-08-13; the R preparation workflow
#' and exact GDC manifest are kept under `data-raw/` in the source repository.
#'
#' @examples
#' data(pik3ca_tcga_brca)
#' head(pik3ca_tcga_brca)
#' @keywords datasets
"pik3ca_tcga_brca"
