#' Draw an interactive protein lollipop plot
#'
#' Creates a GenomeSpy protein-mutation lollipop plot from a `maftools` MAF
#' object or an ordinary data frame. The basic layout follows
#' [maftools::lollipopPlot()], while the displaced layout separates dense
#' hotspots and connects every marker back to its true protein position.
#'
#' @param maf A maftools `MAF` object.
#' @param data Optional mutation data frame, following `maftools::lollipopPlot()`.
#'   MutGlyph accepts its two-column position/count convention as well as named
#'   `position`, `mutation`, `variant_class` (or `classification`), `sample`,
#'   `gene`, and `count` columns.
#' @param gene One gene symbol. Required for MAF input; optional when a custom
#'   data frame contains exactly one value in its `gene` column.
#' @param AACol Optional column containing protein changes. With MAF input,
#'   `HGVSp_Short`, `Protein_Change`, and `AAChange` are tried in that order.
#' @param labelPos Amino-acid positions to label, or `"all"`. The displaced
#'   layout labels all mutations by default; the basic layout labels none.
#' @param labPosSize Relative mutation-label size, matching maftools' `cex`
#'   semantics.
#' @param collapsePosLabel Combine mutation labels at the same amino-acid
#'   position, for example `D835Y/H`. Used by the basic layout.
#' @param labPosAngle Mutation-label angle in degrees. Positive values rotate
#'   counterclockwise, as in maftools. Used by the basic layout.
#' @param showMutationRate Include the mutated-sample fraction in the title.
#' @param showTitle Show the autogenerated plot title and identifier subtitle.
#' @param showDomainLabel Draw ranged labels inside protein domains.
#' @param refSeqID,proteinID Optional RefSeq transcript or protein identifier.
#'   These retain maftools' domain-selection semantics. If compatible RefSeq
#'   metadata is present in the mutation input, MutGlyph warns about mixed or
#'   mismatching isoforms without silently filtering mutations.
#' @param colors Optional named character vector overriding mutation-class
#'   colors.
#' @param domains Optional custom domain data frame with `start`, `end`, and
#'   `label` columns. `description` and `protein_length` are optional.
#' @param proteinLength Optional protein length in amino acids.
#' @param layout Either `"basic"` for true-position vertical lollipops or
#'   `"displaced"` for collision-aware markers, labels, and connectors.
#' @param count Use mutation `"events"` (the maftools convention) or distinct
#'   tumor `"samples"` for recurrence heights. For a pre-aggregated data frame,
#'   this also defines what its `count` column represents.
#' @param minCount Minimum plotted recurrence under the selected `count` mode.
#'   When `NULL`, the basic layout uses one and the displaced layout uses two.
#' @param yScale `"linear"` or `"log"`. When `NULL`, basic plots use linear
#'   and displaced plots use logarithmic scaling.
#' @param showLegend Show the mutation-class legend.
#' @param pointSize Relative marker-size multiplier, matching maftools' linear
#'   `cex` semantics.
#' @param topPadding Vertical space in pixels reserved above the mutation panel
#'   for mutation labels. When `NULL`, the basic layout uses 10 pixels and the
#'   displaced layout uses 70 pixels.
#' @param width,height Widget dimensions.
#' @param elementId Optional element ID.
#'
#' @details
#' With MAF input and no `domains`, protein domains are read from maftools'
#' bundled `protein_domains.RDs` snapshot. Custom data without domains is drawn
#' against a plain protein backbone. [mutglyph_interpro_domains()] returns a
#' compatible domain table when online InterPro annotations are desired.
#' When no identifier is supplied, MutGlyph follows maftools by selecting the
#' longest bundled protein model (and the first transcript when lengths tie).
#' The subtitle labels selected transcript and protein identifiers, for example
#' `Transcript: NM_004119; Protein: NP_004110`.
#'
#' Mutation event and distinct-sample counts are both retained in
#' `plot$x$spec$datasets$mutations`, irrespective of which one is plotted.
#'
#' @return A MutGlyph htmlwidget.
#' @seealso [oncoplot()], [rainfallPlot()], and [as_json()].
#'
#' @examples
#' if (interactive()) {
#'   laml <- maftools::read.maf(
#'     maf = system.file("extdata", "tcga_laml.maf.gz", package = "maftools"),
#'     verbose = FALSE
#'   )
#'   # Frozen InterPro representative-domain matches for UniProt P36888.
#'   # Fetch current matches with mutglyph_interpro_domains("P36888").
#'   flt3_domains <- data.frame(
#'     start = c(246, 438, 564, 756),
#'     end = c(357, 531, 695, 958),
#'     label = c("Ig-like", "Ig-like", "Kinase N", "Kinase C"),
#'     protein_length = 993
#'   )
#'   lollipopPlot(
#'     laml,
#'     gene = "FLT3",
#'     AACol = "Protein_Change",
#'     domains = flt3_domains,
#'     layout = "displaced"
#'   )
#' }
#' @export
lollipopPlot <- function(maf,
                         data = NULL,
                         gene = NULL,
                         AACol = NULL,
                         labelPos = NULL,
                         labPosSize = 0.9,
                         showMutationRate = TRUE,
                         showTitle = TRUE,
                         showDomainLabel = TRUE,
                         refSeqID = NULL,
                         proteinID = NULL,
                         colors = NULL,
                         domains = NULL,
                         proteinLength = NULL,
                         layout = c("basic", "displaced"),
                         count = c("events", "samples"),
                         minCount = NULL,
                         yScale = NULL,
                         showLegend = TRUE,
                         collapsePosLabel = TRUE,
                         labPosAngle = 0,
                         pointSize = 1.5,
                         topPadding = NULL,
                         width = NULL,
                         height = NULL,
                         elementId = NULL) {
  has_maf <- !missing(maf) && !is.null(maf)
  has_data <- !is.null(data)
  if (has_maf == has_data) {
    stop("Supply exactly one of `maf` and `data`.", call. = FALSE)
  }
  if (has_maf && !inherits(maf, "MAF")) {
    stop("`maf` must be a maftools MAF object; use `data` for a data frame.", call. = FALSE)
  }
  if (has_data && !is.data.frame(data)) {
    stop("`data` must be a data frame.", call. = FALSE)
  }
  input <- if (has_maf) maf else data
  layout <- match.arg(layout)
  count <- match.arg(count)
  if (!is.null(yScale)) yScale <- match.arg(yScale, c("linear", "log"))
  mutglyph_flag(showMutationRate, "showMutationRate")
  mutglyph_flag(showTitle, "showTitle")
  mutglyph_flag(showDomainLabel, "showDomainLabel")
  mutglyph_flag(showLegend, "showLegend")
  mutglyph_flag(collapsePosLabel, "collapsePosLabel")
  mutglyph_positive_number(labPosSize, "labPosSize")
  if (
    length(labPosAngle) != 1L || !is.numeric(labPosAngle) ||
      is.na(labPosAngle) || !is.finite(labPosAngle)
  ) {
    stop("`labPosAngle` must be one finite number.", call. = FALSE)
  }
  mutglyph_positive_number(pointSize, "pointSize")
  if (is.null(topPadding)) {
    topPadding <- if (layout == "basic") 10 else 70
  } else if (
    length(topPadding) != 1L || !is.numeric(topPadding) ||
      is.na(topPadding) || !is.finite(topPadding) || topPadding < 0
  ) {
    stop("`topPadding` must be one finite non-negative number or NULL.", call. = FALSE)
  }
  data <- lollipop_data(
    input,
    gene = gene,
    AACol = AACol,
    refSeqID = refSeqID,
    proteinID = proteinID,
    domains = domains,
    proteinLength = proteinLength,
    count = count,
    colors = colors
  )
  if (is.null(minCount)) {
    minCount <- if (layout == "displaced") 2 else 1
  } else if (
    length(minCount) != 1L || !is.numeric(minCount) || is.na(minCount) ||
      !is.finite(minCount) || minCount < 1 || minCount != floor(minCount)
  ) {
    stop("`minCount` must be one positive integer or NULL.", call. = FALSE)
  }
  data$mutations <- data$mutations[
    data$mutations$count >= minCount,
    ,
    drop = FALSE
  ]
  if (nrow(data$mutations) == 0L) {
    stop(
      sprintf("No mutations have a recurrence of at least %d.", minCount),
      call. = FALSE
    )
  }
  data$mutations$label <- lollipop_labels(
    data$mutations,
    labelPos = labelPos,
    layout = layout,
    collapsePosLabel = collapsePosLabel
  )
  mutglyph_widget(
    lollipop_spec(
      data,
      layout = layout,
      yScale = yScale,
      showMutationRate = showMutationRate,
      showTitle = showTitle,
      showDomainLabel = showDomainLabel,
      showLegend = showLegend,
      labPosSize = labPosSize,
      labPosAngle = labPosAngle,
      pointSize = pointSize,
      topPadding = topPadding
    ),
    width = width,
    height = height,
    elementId = elementId
  )
}

lollipop_labels <- function(mutations,
                            labelPos,
                            layout,
                            collapsePosLabel = TRUE) {
  if (is.null(labelPos)) {
    return(if (layout == "displaced") {
      lollipop_abbreviate_labels(mutations$mutation)
    } else {
      rep("", nrow(mutations))
    })
  }
  if (is.character(labelPos)) {
    if (length(labelPos) != 1L || is.na(labelPos) || labelPos != "all") {
      stop("`labelPos` must be numeric amino-acid positions or \"all\".", call. = FALSE)
    }
    selected <- rep(TRUE, nrow(mutations))
  } else {
    if (!is.numeric(labelPos) || length(labelPos) == 0L || anyNA(labelPos)) {
      stop("`labelPos` must be numeric amino-acid positions or \"all\".", call. = FALSE)
    }
    selected <- mutations$position %in% labelPos
    if (!any(selected)) {
      stop("None of the requested `labelPos` positions is mutated.", call. = FALSE)
    }
  }

  labels <- rep("", nrow(mutations))
  if (layout != "basic" || !collapsePosLabel) {
    labels[selected] <- lollipop_abbreviate_labels(mutations$mutation[selected])
    return(labels)
  }

  # maftools 2.26.0 collapses changes at a shared residue into one label.
  # Attach it to the tallest lollipop so its vertical position clears every
  # point while preserving the same user-facing label semantics.
  for (position in unique(mutations$position[selected])) {
    indices <- which(selected & mutations$position == position)
    anchor <- indices[which.max(mutations$count[indices])]
    labels[anchor] <- lollipop_collapse_position_labels(
      mutations$mutation[indices]
    )
  }
  labels
}

lollipop_collapse_position_labels <- function(labels) {
  labels <- unique(as.character(labels))
  if (length(labels) == 1L) {
    return(lollipop_abbreviate_labels(labels))
  }
  # Keep the first complete change and remove the shared residue prefix from
  # subsequent changes, falling back to the original label when it has no
  # recognizable amino-acid/position prefix.
  suffixes <- sub("^[[:alpha:]*]+[[:digit:]]+", "", labels[-1L])
  suffixes[!nzchar(suffixes)] <- labels[-1L][!nzchar(suffixes)]
  lollipop_abbreviate_labels(paste(c(labels[1L], suffixes), collapse = "/"))
}

lollipop_abbreviate_labels <- function(labels, maximum = 18L) {
  # Keep labels within the fixed displaced-label gutter. ASCII dots render in
  # GenomeSpy's limited font atlas more reliably than a Unicode ellipsis.
  ifelse(
    nchar(labels) <= maximum,
    labels,
    paste0(substr(labels, 1L, maximum - 3L), "...")
  )
}
