#' Compare two cohorts with an interactive protein lollipop plot
#'
#' Creates a mirrored GenomeSpy lollipop plot corresponding to
#' [maftools::lollipopPlot2()]. Mutations from `m1` are drawn above a shared
#' protein model and mutations from `m2` below it.
#'
#' @param m1,m2 maftools `MAF` objects or ordinary mutation data frames.
#' @param gene One gene symbol.
#' @param AACol1,AACol2 Optional protein-change columns for `m1` and `m2`.
#' @param m1_name,m2_name Optional cohort names.
#' @param m1_label,m2_label Amino-acid positions to label for each cohort, or
#'   `"all"`.
#' @param refSeqID,proteinID Optional RefSeq transcript or protein identifier
#'   selecting the shared protein model.
#' @param labPosAngle Mutation-label angle in degrees. Positive values rotate
#'   counterclockwise, as in maftools.
#' @param labPosSize Relative mutation-label size, matching maftools' `cex`
#'   semantics.
#' @param colors Optional named character vector overriding mutation-class
#'   colors.
#' @param pointSize Relative marker-size multiplier, matching maftools' linear
#'   `cex` semantics.
#' @param showDomainLabel Draw ranged labels inside protein domains.
#' @param showTitle Show the autogenerated plot title and identifier subtitle.
#' @param domains Optional custom domain data frame with `start`, `end`, and
#'   `label` columns.
#' @param proteinLength Optional protein length in amino acids.
#' @param count Use mutation `"events"` (the maftools convention) or distinct
#'   tumor `"samples"` for recurrence heights.
#' @param showLegend Show the mutation-class legend.
#' @param width,height Widget dimensions.
#' @param elementId Optional element ID.
#'
#' @details
#' Both cohorts use one protein coordinate system and independently scaled
#' recurrence axes. One cohort may contain no mutations for the selected gene.
#'
#' Both stem sets extend to the center of the shared protein track, and the
#' protein track is rendered above them at the overlap.
#'
#' @return A MutGlyph htmlwidget.
#' @seealso [lollipopPlot()], [maftools::lollipopPlot2()]
#'
#' @examples
#' if (interactive()) {
#'   primary <- maftools::read.maf(
#'     system.file("extdata", "APL_primary.maf.gz", package = "maftools"),
#'     verbose = FALSE
#'   )
#'   relapse <- maftools::read.maf(
#'     system.file("extdata", "APL_relapse.maf.gz", package = "maftools"),
#'     verbose = FALSE
#'   )
#'   lollipopPlot2(
#'     m1 = primary,
#'     m2 = relapse,
#'     gene = "FLT3",
#'     AACol1 = "amino_acid_change",
#'     AACol2 = "amino_acid_change",
#'     m1_name = "Primary",
#'     m2_name = "Relapse",
#'     m1_label = 835,
#'     m2_label = 835
#'   )
#' }
#' @export
lollipopPlot2 <- function(m1,
                          m2,
                          gene = NULL,
                          AACol1 = NULL,
                          AACol2 = NULL,
                          m1_name = NULL,
                          m2_name = NULL,
                          m1_label = NULL,
                          m2_label = NULL,
                          refSeqID = NULL,
                          proteinID = NULL,
                          labPosAngle = 0,
                          labPosSize = 0.9,
                          colors = NULL,
                          pointSize = 1.2,
                          showDomainLabel = TRUE,
                          domains = NULL,
                          proteinLength = NULL,
                          count = c("events", "samples"),
                          showLegend = TRUE,
                          showTitle = TRUE,
                          width = NULL,
                          height = NULL,
                          elementId = NULL) {
  inputs <- list(m1 = m1, m2 = m2)
  for (argument in names(inputs)) {
    value <- inputs[[argument]]
    if (!inherits(value, "MAF") && !is.data.frame(value)) {
      stop(sprintf("`%s` must be a maftools MAF object or a data frame.", argument), call. = FALSE)
    }
  }
  gene <- lollipop_string(gene, "gene")
  if (!is.null(m1_name)) m1_name <- lollipop_string(m1_name, "m1_name")
  if (!is.null(m2_name)) m2_name <- lollipop_string(m2_name, "m2_name")
  count <- match.arg(count)
  mutglyph_flag(showDomainLabel, "showDomainLabel")
  mutglyph_flag(showLegend, "showLegend")
  mutglyph_flag(showTitle, "showTitle")
  mutglyph_positive_number(labPosSize, "labPosSize")
  mutglyph_positive_number(pointSize, "pointSize")
  if (
    length(labPosAngle) != 1L || !is.numeric(labPosAngle) ||
      is.na(labPosAngle) || !is.finite(labPosAngle)
  ) {
    stop("`labPosAngle` must be one finite number.", call. = FALSE)
  }

  data <- lollipop2_data(
    m1,
    m2,
    gene = gene,
    AACol1 = AACol1,
    AACol2 = AACol2,
    m1_name = m1_name,
    m2_name = m2_name,
    m1_label = m1_label,
    m2_label = m2_label,
    refSeqID = refSeqID,
    proteinID = proteinID,
    colors = colors,
    domains = domains,
    proteinLength = proteinLength,
    count = count
  )
  mutglyph_widget(
    lollipop2_spec(
      data,
      showDomainLabel = showDomainLabel,
      showTitle = showTitle,
      showLegend = showLegend,
      labPosSize = labPosSize,
      labPosAngle = labPosAngle,
      pointSize = pointSize
    ),
    width = width,
    height = height,
    elementId = elementId
  )
}
