#' Draw an interactive rainfall plot
#'
#' Creates a GenomeSpy rainfall plot from a `maftools` MAF object. The API
#' deliberately follows [maftools::rainfallPlot()] where practical, making the
#' function an almost drop-in interactive replacement.
#'
#' @param maf A maftools `MAF` object.
#' @param tsb One tumor sample barcode. When `NULL`, the most mutated sample is
#'   selected.
#' @param showTitle Show the autogenerated sample title.
#' @param detectChangePoints Detect and annotate potential kataegis loci using
#'   the maftools criterion: at least six consecutive mutations with an average
#'   intermutation distance no greater than 1,000 bp.
#' @param ref.build Reference assembly: `"hg18"`, `"hg19"`, or `"hg38"`.
#' @param color Optional named character vector overriding colors for the six
#'   pyrimidine substitution classes.
#' @param savePlot Retained for maftools API familiarity. `TRUE` is unsupported;
#'   use the widget's **Save as SVG** button instead.
#' @param width,height Widget dimensions. Unlike maftools, these do not describe
#'   a PDF device.
#' @param fontSize Relative font-size multiplier.
#' @param pointSize Relative mutation-point size.
#' @param region Optional initial genomic region such as
#'   `"chr8:98000000-98500000"`, or a chromosome such as `"chr8"`. Commas and
#'   whitespace in coordinates are accepted. The endpoints may span
#'   chromosomes, for example `"chr3:43393228-chr4:8534670"`. The plot remains
#'   zoomable.
#' @param elementId Optional element ID.
#'
#' @details
#' Only SNP records are plotted, including synonymous variants. Substitutions
#' are normalized to the six pyrimidine classes. Inter-event distances are
#' calculated independently within each chromosome, so chromosome boundaries
#' do not create artificial distances.
#'
#' With `detectChangePoints = TRUE`, detected kataegis intervals are shaded and
#' marked with upward arrows. The complete locus table is retained in
#' `plot$x$spec$datasets$kataegis` and no files are written as a side effect.
#'
#' @return A MutGlyph htmlwidget.
#' @seealso [oncoplot()] and [as_json()].
#'
#' @examples
#' if (interactive()) {
#'   brca <- maftools::read.maf(
#'     maf = system.file("extdata", "brca.maf.gz", package = "maftools"),
#'     verbose = FALSE
#'   )
#'   rainfallPlot(brca, detectChangePoints = TRUE)
#' }
#' @export
rainfallPlot <- function(maf,
                         tsb = NULL,
                         showTitle = TRUE,
                         detectChangePoints = FALSE,
                         ref.build = "hg19",
                         color = NULL,
                         savePlot = FALSE,
                         width = NULL,
                         height = NULL,
                         fontSize = 1.2,
                         pointSize = 0.4,
                         region = NULL,
                         elementId = NULL) {
  mutglyph_flag(savePlot, "savePlot")
  mutglyph_flag(showTitle, "showTitle")
  if (savePlot) {
    stop(
      "`savePlot = TRUE` is not supported; use the widget's Save as SVG button.",
      call. = FALSE
    )
  }
  mutglyph_positive_number(fontSize, "fontSize")
  mutglyph_positive_number(pointSize, "pointSize")
  data <- rainfall_data(
    maf,
    tsb = tsb,
    detectChangePoints = detectChangePoints,
    ref.build = ref.build,
    color = color
  )
  mutglyph_widget(
    rainfall_spec(
      data,
      fontSize = fontSize,
      pointSize = pointSize,
      showTitle = showTitle,
      region = region
    ),
    width = width,
    height = height,
    elementId = elementId
  )
}
